### ISSUE TITLE
Alternative data presentation

### ISSUE THREAD

**Issue by livtanong** [by-implication/Badger#10]
http://www.gov.ph/directory/

agency-based.

**Comment by ahelpingchip** [comment]
Actually, if you don't mind, this dovetails very nicely with the visualization I had planned for the home/landing page. 

The one like Bret Victor's graphs in _Our Choice_. On my phone so I can't give you a link or screenshot. 

EDIT: I found it, please refer to the other issue (#11)

**Comment by livtanong** [comment]
make it so!

**Comment by ghost** [comment]
merging into #11
