### ISSUE TITLE
Occasional error when refreshing: NoSuchElementException: key not found: SOURCE

### ISSUE THREAD

**Issue by livtanong** [by-implication/Badger#15]
java.util.NoSuchElementException: key not found: SOURCE
     scala.collection.MapLike$class.default(MapLike.scala:228)
     scala.collection.AbstractMap.default(Map.scala:58)
     scala.collection.MapLike$class.apply(MapLike.scala:141)
     scala.collection.AbstractMap.apply(Map.scala:58)
     play.templates.GeneratedSource.source(ScalaTemplateCompiler.scala:127)
     play.templates.GeneratedSource.needRecompilation(ScalaTemplateCompiler.scala:112)
     play.templates.ScalaTemplateCompiler$.compile(ScalaTemplateCompiler.scala:177)
     play.PlaySourceGenerators$$anonfun$3$$anonfun$apply$8$$anonfun$apply$9.apply(PlaySourceGenerators.scala:45)
     play.PlaySourceGenerators$$anonfun$3$$anonfun$apply$8$$anonfun$apply$9.apply(PlaySourceGenerators.scala:43)
     scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
     scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
     play.PlaySourceGenerators$$anonfun$3$$anonfun$apply$8.apply(PlaySourceGenerators.scala:43)
     play.PlaySourceGenerators$$anonfun$3$$anonfun$apply$8.apply(PlaySourceGenerators.scala:42)
     scala.collection.immutable.List.foreach(List.scala:318)
     play.PlaySourceGenerators$$anonfun$3.apply(PlaySourceGenerators.scala:42)
     play.PlaySourceGenerators$$anonfun$3.apply(PlaySourceGenerators.scala:30)
     scala.Function5$$anonfun$tupled$1.apply(Function5.scala:35)
     scala.Function5$$anonfun$tupled$1.apply(Function5.scala:34)
     scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
     sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
     sbt.std.Transform$$anon$4.work(System.scala:64)
     sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
     sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
     sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
     sbt.Execute.work(Execute.scala:244)
     sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
     sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
     sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
     sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
     java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
     java.util.concurrent.FutureTask.run(FutureTask.java:138)
     java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
     java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
     java.util.concurrent.FutureTask.run(FutureTask.java:138)
     java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
     java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
     java.lang.Thread.run(Thread.java:695)

**Comment by livtanong** [comment]
To fix, i have to change the URL back to localhost:9000

**Comment by ghost** [comment]
sterile, wontfix

**Comment by livtanong** [comment]
Still happens to me though. —
Levi
