### ISSUE TITLE
Is home page / breakdown beta-ready?

### ISSUE THREAD

**Issue by livtanong** [by-implication/Badger#31]
I don't see much activity on either page, and I'm thinking maybe we should remove/hide the two, if they won't be complete by the 16th.

Also, energy spent working on these might be better spent making an about page (not like the splash page we have now) talking about open data, the hackathon, our company, and the purpose of Badger. Also, issue #30.

attn: @ahelpingchip @syk0saje @xzq381

**Comment by ghost** [comment]
i agree that we should have an about page. hiding the links is trivial and can easily be done once we have to.
