### ISSUE TITLE
Can has boolean or count for map pins

### ISSUE THREAD

**Issue by livtanong** [by-implication/Badger#35]
- so can say ‘this thing doesn’t have a location yet. pin this location!’
- ‘this location is contested between N clusters. where do you think it is?’

**Comment by ghost** [comment]
you get a count, which doubles as a boolean because javascript! \o/

**Comment by ghost** [comment]
hint: focus.value.clicks is the click count, focus.value.userClick can be used as boolean to tell whether or not the user has clicked this leaf
